bar = uint

foo = {
	x : bar,
;	y : [[uint]],
	z : uint,
	0 : tstr
}

block = {
	header : uint,
;	bodies : [* body],
;	metadata : { * uint => uint }
}

;body = (
;	txs : [+uint]
;)

mapper = { * tstr => uint }
